version: "2.22.0-desktop.2"
services:
  backend:
    container_name: "backend-container"
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    expose:
      - 8080
    volumes:
      - "linktoshrink-volume:/data/backend"
    networks:
      - linktoshrink-network
    depends_on:
      - redis
    restart: always
    ports:
      - 8080:8080
  redis:
    image: "redis"
    container_name: "redis-container"
    expose:
      - 6379
    volumes:
      - "linktoshrink-volume:/data/redis"
    networks:
      - linktoshrink-network
    env_file:
      - ./backend/.env
    ports:
      - 6379:6379
  frontend:
    container_name: "frontend-container"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    expose:
      - 3000
    volumes:
      - "linktoshrink-volume:/data/frontend"
    networks:
      - linktoshrink-network
    depends_on:
      - backend
    restart: always
    ports:
      - 3000:3000
volumes:
  linktoshrink-volume:
networks:
  linktoshrink-network:
